services:
  backend:
    image: lehrstuhlkesdogan/tagteam-backend:latest
    build: ./backend
    pull_policy: build
    ports:
      - "8000:8000"
    volumes:
      - ./data/backend:${MEDIA_DIR}
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: lehrstuhlkesdogan/tagteam-frontend:latest
    build: ./frontend
    pull_policy: build
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes --save 60 1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5