apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tagteams
resources:
  - ../../base
images:
  - name: lehrstuhlkesdogan/tagteams-backend
    newTag: latest
  - name: lehrstuhlkesdogan/tagteams-frontend
    newTag: latest
